### ISSUE TITLE
i did this, we could build on top

### ISSUE THREAD

**Issue by hypnopump** [lucidrains/memory-efficient-attention-pytorch#1]
Hi there!

It seems I did already some of the code... https://github.com/CHARM-Tx/linear_mem_attention_pytorch could we build on top of this? I talked to https://github.com/Chillee about an experimental functionality from functorch: https://github.com/pytorch/functorch that would allow for increased speed (mainly i want to match jax perofmance but its just difficult w/ pytorch imperative style). 

I would love to collaborate on this if you want!

**Comment by lucidrains** [comment]
oh hey! yea I know, but I may be taking this a different direction, with Triton or CUDA code in the worst case

have you found any success with this technique?

**Comment by lucidrains** [comment]
what did Horace say about using functorch? I don't think it will be too helpful here

**Comment by hypnopump** [comment]
there's a functionality to fuse kernels in functorch now: https://github.com/pytorch/functorch/blob/main/notebooks/aot_autograd_optimizations.ipynb mainly i tried to use that...
but yea triton might be good/better, since functorch is somewhat experimental atm

**Comment by lucidrains** [comment]
@hypnopump yea, i think Triton is the better bet, as they are actually being used by companies whose underlying business model depends on attention

**Comment by lucidrains** [comment]
@hypnopump oh, functorch just reached 0.1.0 https://pytorch.org/blog/pytorch-1.11-released/ do you want to reach out to Horace and see if it works now?
